/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author admin
 */
public class ViewShop extends javax.swing.JFrame {

    /**
     * Creates new form ViewShop
     */
    public ViewShop() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        JLBanHang = new javax.swing.JLabel();
        JLSanPham = new javax.swing.JLabel();
        JLKhuyenMai = new javax.swing.JLabel();
        JLNhanVien = new javax.swing.JLabel();
        JLThongKe = new javax.swing.JLabel();
        JLKhachHang = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        JLBanHang.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        JLBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBanHang.setText("Bán hàng");
        JLBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLBanHangMouseExited(evt);
            }
        });

        JLSanPham.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        JLSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLSanPham.setText("Sản phẩm");
        JLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLSanPhamMouseExited(evt);
            }
        });

        JLKhuyenMai.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        JLKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLKhuyenMai.setText("Khuyến mãi");
        JLKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLKhuyenMaiMouseExited(evt);
            }
        });

        JLNhanVien.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        JLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLNhanVien.setText("Nhân viên");
        JLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLNhanVienMouseExited(evt);
            }
        });

        JLThongKe.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        JLThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLThongKe.setText("Thống kê");
        JLThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLThongKeMouseExited(evt);
            }
        });

        JLKhachHang.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        JLKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLKhachHang.setText("Khách hàng");
        JLKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLKhachHangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(JLThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(JLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(JLKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(JLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 204, 255));

        jLabel29.setText("Shop Ban giay");

        jLabel30.setText("X");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLKhuyenMaiMouseClicked
        ViewKhuyenMai1 thongtin = new ViewKhuyenMai1();
        thongtin.setVisible(true);
        thongtin.pack();
        thongtin.setLocationRelativeTo(null);
        thongtin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JLKhuyenMaiMouseClicked

    private void JLKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLKhuyenMaiMouseEntered
        JLKhuyenMai.setLayout(new BorderLayout(10, 10));
        JLKhuyenMai.setBorder(BorderFactory.createEtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_JLKhuyenMaiMouseEntered

    private void JLKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLKhuyenMaiMouseExited
        JLKhuyenMai.setLayout(null);
        JLKhuyenMai.setBorder(null);
    }//GEN-LAST:event_JLKhuyenMaiMouseExited

    private void JLBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBanHangMouseClicked
        ViewBanHang banHang = new ViewBanHang();
        banHang.setVisible(true);
        banHang.pack();
        banHang.setLocationRelativeTo(null);
        banHang.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JLBanHangMouseClicked

    private void JLBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBanHangMouseEntered
        JLBanHang.setLayout(new BorderLayout(10, 10));
        JLBanHang.setBorder(BorderFactory.createEtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_JLBanHangMouseEntered

    private void JLBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBanHangMouseExited
        JLBanHang.setLayout(null);
        JLBanHang.setBorder(null);
    }//GEN-LAST:event_JLBanHangMouseExited

    private void JLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLSanPhamMouseClicked
        ViewSanPham sp = new ViewSanPham();
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JLSanPhamMouseClicked

    private void JLSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLSanPhamMouseEntered
        JLSanPham.setLayout(new BorderLayout(10, 10));
        JLSanPham.setBorder(BorderFactory.createEtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_JLSanPhamMouseEntered

    private void JLSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLSanPhamMouseExited
        JLSanPham.setLayout(null);
        JLSanPham.setBorder(null);
    }//GEN-LAST:event_JLSanPhamMouseExited

    private void JLNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLNhanVienMouseClicked
        ViewNhanVien nv = new ViewNhanVien();
        nv.setVisible(true);
        nv.pack();
        nv.setLocationRelativeTo(null);
        nv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JLNhanVienMouseClicked

    private void JLNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLNhanVienMouseEntered
        JLNhanVien.setLayout(new BorderLayout(10, 10));
        JLNhanVien.setBorder(BorderFactory.createEtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_JLNhanVienMouseEntered

    private void JLNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLNhanVienMouseExited
        JLNhanVien.setLayout(null);
        JLNhanVien.setBorder(null);
    }//GEN-LAST:event_JLNhanVienMouseExited

    private void JLKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLKhachHangMouseClicked
        ViewKhachHang kh = new ViewKhachHang();
        kh.setVisible(true);
        kh.pack();
        kh.setLocationRelativeTo(null);
        kh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JLKhachHangMouseClicked

    private void JLKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLKhachHangMouseEntered
        JLKhachHang.setLayout(new BorderLayout(10, 10));
        JLKhachHang.setBorder(BorderFactory.createEtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_JLKhachHangMouseEntered

    private void JLKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLKhachHangMouseExited
        JLKhachHang.setLayout(null);
        JLKhachHang.setBorder(null);
    }//GEN-LAST:event_JLKhachHangMouseExited

    private void JLThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLThongKeMouseClicked
        ViewThongKe tk = new ViewThongKe();
        tk.setVisible(true);
        tk.pack();
        tk.setLocationRelativeTo(null);
        tk.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JLThongKeMouseClicked

    private void JLThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLThongKeMouseEntered
        JLThongKe.setLayout(new BorderLayout(10, 10));
        JLThongKe.setBorder(BorderFactory.createEtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_JLThongKeMouseEntered

    private void JLThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLThongKeMouseExited
        JLThongKe.setLayout(null);
        JLThongKe.setBorder(null);
    }//GEN-LAST:event_JLThongKeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBanHang;
    private javax.swing.JLabel JLKhachHang;
    private javax.swing.JLabel JLKhuyenMai;
    private javax.swing.JLabel JLNhanVien;
    private javax.swing.JLabel JLSanPham;
    private javax.swing.JLabel JLThongKe;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
